package tui

import (
	"encoding/json"
	"fmt"
	"regexp"
	"strings"

	"github.com/safedoor/ostui/internal/db"
)

// nixHashRe matches a 32-char nix store hash followed by a hyphen in rule names.
// Group 1 captures the leading separator (hyphen or start-of-string) to preserve it.
var nixHashRe = regexp.MustCompile(`(^|-)[a-z0-9]{32}-`)

// subOperator is the JSON structure stored in OpData for list-type operators.
type subOperator struct {
	Type      string        `json:"type"`
	Operand   string        `json:"operand"`
	Data      string        `json:"data"`
	Sensitive bool          `json:"sensitive"`
	List      []subOperator `json:"list,omitempty"`
}

// cleanNixAttrName strips 32-char nix store hashes from a rule name
// to produce a shorter, more readable Nix attribute key.
func cleanNixAttrName(name string) string {
	cleaned := nixHashRe.ReplaceAllString(name, "${1}")
	cleaned = strings.TrimLeft(cleaned, "-")
	return cleaned
}

// nixProcessComment returns a short "# basename" comment if the rule's
// operator data contains a nix store path for process.path, or empty string.
func nixProcessComment(r db.RuleRow) string {
	if r.OpOperand == "process.path" && strings.HasPrefix(r.OpData, "/nix/store/") {
		return extractProcessName(r.OpData)
	}
	return ""
}

// ExportRulesToNix formats rules as a NixOS services.opensnitch.rules attribute set.
func ExportRulesToNix(rules []db.RuleRow) string {
	var b strings.Builder
	b.WriteString("# Generated by ostui — use as services.opensnitch.rules\n")
	b.WriteString("{\n")

	// Build unique attribute keys, deduplicating cleaned names.
	attrKeys := make([]string, len(rules))
	seen := make(map[string]int)
	for i, r := range rules {
		key := cleanNixAttrName(r.Name)
		if key == "" {
			key = r.Name
		}
		if n, ok := seen[key]; ok {
			seen[key] = n + 1
			key = fmt.Sprintf("%s-%d", key, n+1)
		} else {
			seen[key] = 1
		}
		attrKeys[i] = key
	}

	for i, r := range rules {
		// Add a comment with the binary basename for nix store process rules.
		if comment := nixProcessComment(r); comment != "" {
			b.WriteString(fmt.Sprintf("  # %s\n", comment))
		}

		name := nixAttrName(attrKeys[i])
		b.WriteString(fmt.Sprintf("  %s = {\n", name))
		b.WriteString(fmt.Sprintf("    name = %s;\n", nixString(r.Name)))
		b.WriteString(fmt.Sprintf("    enabled = %s;\n", nixBool(r.Enabled)))
		b.WriteString(fmt.Sprintf("    action = %s;\n", nixString(r.Action)))
		b.WriteString(fmt.Sprintf("    duration = %s;\n", nixString(r.Duration)))

		if r.Precedence == "true" {
			b.WriteString("    precedence = true;\n")
		}
		if r.Nolog == "true" {
			b.WriteString("    nolog = true;\n")
		}

		writeOperator(&b, r.OpType, r.OpSensitive, r.OpOperand, r.OpData, "    ")

		b.WriteString("  };\n")
	}

	b.WriteString("}\n")
	return b.String()
}

// writeOperator renders an operator block. For list-type operators, it parses
// the JSON data and renders sub-operators as a Nix list attribute.
func writeOperator(b *strings.Builder, opType, opSensitive, opOperand, opData, indent string) {
	b.WriteString(fmt.Sprintf("%soperator = {\n", indent))
	inner := indent + "  "

	b.WriteString(fmt.Sprintf("%stype = %s;\n", inner, nixString(opType)))
	b.WriteString(fmt.Sprintf("%ssensitive = %s;\n", inner, nixBool(opSensitive)))
	b.WriteString(fmt.Sprintf("%soperand = %s;\n", inner, nixString(opOperand)))

	if opType == "list" || opType == "lists" {
		var subs []subOperator
		if err := json.Unmarshal([]byte(opData), &subs); err == nil && len(subs) > 0 {
			b.WriteString(fmt.Sprintf("%slist = [\n", inner))
			for _, sub := range subs {
				writeSubOperator(b, sub, inner+"  ")
			}
			b.WriteString(fmt.Sprintf("%s];\n", inner))
		} else {
			// Fallback: can't parse as JSON list, emit raw data.
			b.WriteString(fmt.Sprintf("%sdata = %s;\n", inner, nixString(opData)))
		}
	} else {
		b.WriteString(fmt.Sprintf("%sdata = %s;\n", inner, nixString(opData)))
	}

	b.WriteString(fmt.Sprintf("%s};\n", indent))
}

func writeSubOperator(b *strings.Builder, op subOperator, indent string) {
	b.WriteString(fmt.Sprintf("%s{\n", indent))
	inner := indent + "  "

	b.WriteString(fmt.Sprintf("%stype = %s;\n", inner, nixString(op.Type)))
	b.WriteString(fmt.Sprintf("%ssensitive = %s;\n", inner, nixBool(fmt.Sprintf("%t", op.Sensitive))))
	b.WriteString(fmt.Sprintf("%soperand = %s;\n", inner, nixString(op.Operand)))

	if (op.Type == "list" || op.Type == "lists") && len(op.List) > 0 {
		b.WriteString(fmt.Sprintf("%slist = [\n", inner))
		for _, sub := range op.List {
			writeSubOperator(b, sub, inner+"  ")
		}
		b.WriteString(fmt.Sprintf("%s];\n", inner))
	} else {
		b.WriteString(fmt.Sprintf("%sdata = %s;\n", inner, nixString(op.Data)))
	}

	b.WriteString(fmt.Sprintf("%s}\n", indent))
}

// nixString quotes and escapes a string for Nix.
func nixString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "$", "\\$")
	return `"` + s + `"`
}

// nixBool converts a string "true"/"false" to a Nix boolean literal.
func nixBool(s string) string {
	if s == "true" {
		return "true"
	}
	return "false"
}

// nixAttrName returns a valid Nix attribute name, quoting if necessary.
// Nix identifiers: [a-zA-Z_][a-zA-Z0-9_'-]*
func nixAttrName(name string) string {
	if name == "" {
		return `""`
	}
	if !isNixIdent(name) {
		return nixString(name)
	}
	return name
}

func isNixIdent(s string) bool {
	if len(s) == 0 {
		return false
	}
	first := s[0]
	if !((first >= 'a' && first <= 'z') || (first >= 'A' && first <= 'Z') || first == '_') {
		return false
	}
	for i := 1; i < len(s); i++ {
		c := s[i]
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '-' || c == '\'') {
			return false
		}
	}
	return true
}
