package tui

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/safedoor/ostui/internal/db"
)

// subOperator is the JSON structure stored in OpData for list-type operators.
type subOperator struct {
	Type      string        `json:"type"`
	Operand   string        `json:"operand"`
	Data      string        `json:"data"`
	Sensitive bool          `json:"sensitive"`
	List      []subOperator `json:"list,omitempty"`
}

// ExportRulesToNix formats rules as a NixOS services.opensnitch.rules attribute set.
func ExportRulesToNix(rules []db.RuleRow) string {
	var b strings.Builder
	b.WriteString("# Generated by ostui — use as services.opensnitch.rules\n")
	b.WriteString("{\n")

	for _, r := range rules {
		name := nixAttrName(r.Name)
		b.WriteString(fmt.Sprintf("  %s = {\n", name))
		b.WriteString(fmt.Sprintf("    name = %s;\n", nixString(r.Name)))
		b.WriteString(fmt.Sprintf("    enabled = %s;\n", nixBool(r.Enabled)))
		b.WriteString(fmt.Sprintf("    action = %s;\n", nixString(r.Action)))
		b.WriteString(fmt.Sprintf("    duration = %s;\n", nixString(r.Duration)))

		if r.Precedence == "true" {
			b.WriteString("    precedence = true;\n")
		}
		if r.Nolog == "true" {
			b.WriteString("    nolog = true;\n")
		}

		writeOperator(&b, r.OpType, r.OpSensitive, r.OpOperand, r.OpData, "    ")

		b.WriteString("  };\n")
	}

	b.WriteString("}\n")
	return b.String()
}

// writeOperator renders an operator block. For list-type operators, it parses
// the JSON data and renders sub-operators as a Nix list attribute.
func writeOperator(b *strings.Builder, opType, opSensitive, opOperand, opData, indent string) {
	b.WriteString(fmt.Sprintf("%soperator = {\n", indent))
	inner := indent + "  "

	b.WriteString(fmt.Sprintf("%stype = %s;\n", inner, nixString(opType)))
	b.WriteString(fmt.Sprintf("%ssensitive = %s;\n", inner, nixBool(opSensitive)))
	b.WriteString(fmt.Sprintf("%soperand = %s;\n", inner, nixString(opOperand)))

	if opType == "list" || opType == "lists" {
		var subs []subOperator
		if err := json.Unmarshal([]byte(opData), &subs); err == nil && len(subs) > 0 {
			b.WriteString(fmt.Sprintf("%slist = [\n", inner))
			for _, sub := range subs {
				writeSubOperator(b, sub, inner+"  ")
			}
			b.WriteString(fmt.Sprintf("%s];\n", inner))
		} else {
			// Fallback: can't parse as JSON list, emit raw data.
			b.WriteString(fmt.Sprintf("%sdata = %s;\n", inner, nixString(opData)))
		}
	} else {
		b.WriteString(fmt.Sprintf("%sdata = %s;\n", inner, nixString(opData)))
	}

	b.WriteString(fmt.Sprintf("%s};\n", indent))
}

func writeSubOperator(b *strings.Builder, op subOperator, indent string) {
	b.WriteString(fmt.Sprintf("%s{\n", indent))
	inner := indent + "  "

	b.WriteString(fmt.Sprintf("%stype = %s;\n", inner, nixString(op.Type)))
	b.WriteString(fmt.Sprintf("%ssensitive = %s;\n", inner, nixBool(fmt.Sprintf("%t", op.Sensitive))))
	b.WriteString(fmt.Sprintf("%soperand = %s;\n", inner, nixString(op.Operand)))

	if (op.Type == "list" || op.Type == "lists") && len(op.List) > 0 {
		b.WriteString(fmt.Sprintf("%slist = [\n", inner))
		for _, sub := range op.List {
			writeSubOperator(b, sub, inner+"  ")
		}
		b.WriteString(fmt.Sprintf("%s];\n", inner))
	} else {
		b.WriteString(fmt.Sprintf("%sdata = %s;\n", inner, nixString(op.Data)))
	}

	b.WriteString(fmt.Sprintf("%s}\n", indent))
}

// nixString quotes and escapes a string for Nix.
func nixString(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "$", "\\$")
	return `"` + s + `"`
}

// nixBool converts a string "true"/"false" to a Nix boolean literal.
func nixBool(s string) string {
	if s == "true" {
		return "true"
	}
	return "false"
}

// nixAttrName returns a valid Nix attribute name, quoting if necessary.
// Nix identifiers: [a-zA-Z_][a-zA-Z0-9_'-]*
func nixAttrName(name string) string {
	if name == "" {
		return `""`
	}
	if !isNixIdent(name) {
		return nixString(name)
	}
	return name
}

func isNixIdent(s string) bool {
	if len(s) == 0 {
		return false
	}
	first := s[0]
	if !((first >= 'a' && first <= 'z') || (first >= 'A' && first <= 'Z') || first == '_') {
		return false
	}
	for i := 1; i < len(s); i++ {
		c := s[i]
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '-' || c == '\'') {
			return false
		}
	}
	return true
}
